spring:
  application:
    name: gateway

server:
  port: 1110

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1115/eureka/

zuul:
  sensitive-headers: Cookie, Set-Cookie
#host:
#  connect-timeout-millis: 5000
#  socket-timeout-millis: 10000

#zuul.host.max-total-connections: 200
#zuul.host.max-per-route-connections: 20

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

